### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by whereispolaris** [whereispolaris/node-word-guess#5]
- [x]  Read Acceptance Criteria

- [x]  Read Acceptance Criteria Again

- [ ] Go over Pseudo Code

- [ ]  Revise Pseudo Code
